### ISSUE TITLE
[Documentation] Update Item in Accordance with Documentation and README file

### ISSUE THREAD

**Issue by harshsbajwa** [CSC207-2022F-UofT/course-project-my-dog-ate-my-hw#35]
Item currently lacks documentation, it should be created and should be consistent with the current rules.

Additionally, attributes should be privatized to the maximum extent.

**Comment by stephaniesaab** [comment]
Also, the README file should be updated to describe:
1) Project's title
2) Project Description
3) Installation instructions
4) Table of contents if the README is long
5) Instructions to use the program
6) Credits
